import type { ExerciseWithData } from "@/db/types";

export const mockExercises: ExerciseWithData[] = [
  {
    name: "bench press",
    muscleGroups: ["chest"],
    userId: "",
    id: "",
    createdAt: new Date(),
    updatedAt: new Date(),
    data: [
      {
        doneAt: "01/01/01",
        numberOfRepetitions: 10,
        weightLifted: 10,
        exerciseId: "",
        id: "",
        updatedAt: new Date(),
        createdAt: new Date(),
      },
      {
        doneAt: "01/02/01",
        numberOfRepetitions: 20,
        weightLifted: 10,
        exerciseId: "",
        id: "",
        updatedAt: new Date(),
        createdAt: new Date(),
      },
      {
        doneAt: "01/10/01",
        numberOfRepetitions: 30,
        weightLifted: 40,
        exerciseId: "",
        id: "",
        updatedAt: new Date(),
        createdAt: new Date(),
      },
      {
        doneAt: "01/15/01",
        numberOfRepetitions: 20,
        weightLifted: 45,
        exerciseId: "",
        id: "",
        updatedAt: new Date(),
        createdAt: new Date(),
      },
    ],
  },
  {
    name: "squat",
    muscleGroups: ["legs"],
    userId: "",
    id: "",
    createdAt: new Date(),
    updatedAt: new Date(),
    data: [
      {
        doneAt: "01/02/01",
        numberOfRepetitions: 15,
        weightLifted: 20,
        exerciseId: "",
        id: "",
        updatedAt: new Date(),
        createdAt: new Date(),
      },
      {
        doneAt: "01/09/01",
        numberOfRepetitions: 25,
        weightLifted: 20,
        exerciseId: "",
        id: "",
        updatedAt: new Date(),
        createdAt: new Date(),
      },
      {
        doneAt: "01/20/01",
        numberOfRepetitions: 25,
        weightLifted: 30,
        exerciseId: "",
        id: "",
        updatedAt: new Date(),
        createdAt: new Date(),
      },
    ],
  },
  {
    name: "shoulder press",
    muscleGroups: ["shoulders"],
    userId: "",
    id: "",
    createdAt: new Date(),
    updatedAt: new Date(),
    data: [
      {
        doneAt: "01/20/01",
        numberOfRepetitions: 12,
        weightLifted: 18,
        exerciseId: "",
        id: "",
        updatedAt: new Date(),
        createdAt: new Date(),
      },
      {
        doneAt: "01/21/01",
        numberOfRepetitions: 22,
        weightLifted: 30,
        exerciseId: "",
        id: "",
        updatedAt: new Date(),
        createdAt: new Date(),
      },
      {
        doneAt: "01/25/01",
        numberOfRepetitions: 12,
        weightLifted: 18,
        exerciseId: "",
        id: "",
        updatedAt: new Date(),
        createdAt: new Date(),
      },
    ],
  },
  {
    name: "biceps curl",
    muscleGroups: ["biceps"],
    userId: "",
    id: "",
    createdAt: new Date(),
    updatedAt: new Date(),
    data: [
      {
        doneAt: "01/10/01",
        numberOfRepetitions: 8,
        weightLifted: 22,
        exerciseId: "",
        id: "",
        updatedAt: new Date(),
        createdAt: new Date(),
      },
      {
        doneAt: "01/11/01",
        numberOfRepetitions: 8,
        weightLifted: 30,
        exerciseId: "",
        id: "",
        updatedAt: new Date(),
        createdAt: new Date(),
      },
    ],
  },
];
