services:
  database:
    image: postgres:latest
    container_name: gleam_htmx_auth_db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=gleam_htmx_auth
    networks:
      - db

networks:
  db:
