services:
  database:
    image: postgres:latest
    container_name: gym_graphs_db
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}

  cache:
    image: redis:latest
    container_name: gym_graphs_cache
    ports:
      - ${CACHE_PORT}:6379

  # server:
  #   container_name: gym_graphs_server
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile.dev
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./:/app
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - database
