version: '3.9'

services:
  database:
    image: postgres:latest
    container_name: gym_graphs_db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=gym_graphs
