// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account_deletion_sessions.sql

package db

import (
	"context"
)

const createAccountDeletionSession = `-- name: CreateAccountDeletionSession :one
insert into account_deletion_sessions (auth_session_id, secret_hash)
values ($1, $2)
returning id, auth_session_id, secret_hash, user_identity_verified_at, created_at, updated_at
`

type CreateAccountDeletionSessionParams struct {
	AuthSessionID int32
	SecretHash    []byte
}

func (q *Queries) CreateAccountDeletionSession(ctx context.Context, arg CreateAccountDeletionSessionParams) (AccountDeletionSession, error) {
	row := q.db.QueryRow(ctx, createAccountDeletionSession, arg.AuthSessionID, arg.SecretHash)
	var i AccountDeletionSession
	err := row.Scan(
		&i.ID,
		&i.AuthSessionID,
		&i.SecretHash,
		&i.UserIdentityVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAccountDeletionSession = `-- name: DeleteAccountDeletionSession :one
delete from account_deletion_sessions where id = $1 returning id, auth_session_id, secret_hash, user_identity_verified_at, created_at, updated_at
`

func (q *Queries) DeleteAccountDeletionSession(ctx context.Context, id int32) (AccountDeletionSession, error) {
	row := q.db.QueryRow(ctx, deleteAccountDeletionSession, id)
	var i AccountDeletionSession
	err := row.Scan(
		&i.ID,
		&i.AuthSessionID,
		&i.SecretHash,
		&i.UserIdentityVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountDeletionSessionByID = `-- name: GetAccountDeletionSessionByID :one
select id, auth_session_id, secret_hash, user_identity_verified_at, created_at, updated_at from account_deletion_sessions where id = $1 and created_at > now() - interval '1 hour'
`

func (q *Queries) GetAccountDeletionSessionByID(ctx context.Context, id int32) (AccountDeletionSession, error) {
	row := q.db.QueryRow(ctx, getAccountDeletionSessionByID, id)
	var i AccountDeletionSession
	err := row.Scan(
		&i.ID,
		&i.AuthSessionID,
		&i.SecretHash,
		&i.UserIdentityVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markAccountDeletionSessionAsVerified = `-- name: MarkAccountDeletionSessionAsVerified :one
update account_deletion_sessions
set user_identity_verified_at = now()
where id = $1
  and user_identity_verified_at is null
returning id, auth_session_id, secret_hash, user_identity_verified_at, created_at, updated_at
`

func (q *Queries) MarkAccountDeletionSessionAsVerified(ctx context.Context, id int32) (AccountDeletionSession, error) {
	row := q.db.QueryRow(ctx, markAccountDeletionSessionAsVerified, id)
	var i AccountDeletionSession
	err := row.Scan(
		&i.ID,
		&i.AuthSessionID,
		&i.SecretHash,
		&i.UserIdentityVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
