// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_sessions.sql

package db

import (
	"context"
)

const createAuthSession = `-- name: CreateAuthSession :one
insert into auth_sessions (user_id, secret_hash)
values ($1, $2)
returning id, user_id, secret_hash, last_active_at, created_at, updated_at
`

type CreateAuthSessionParams struct {
	UserID     int32
	SecretHash []byte
}

func (q *Queries) CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) (AuthSession, error) {
	row := q.db.QueryRow(ctx, createAuthSession, arg.UserID, arg.SecretHash)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SecretHash,
		&i.LastActiveAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuthSessionByID = `-- name: GetAuthSessionByID :one
select id, user_id, secret_hash, last_active_at, created_at, updated_at from auth_sessions where id = $1
`

func (q *Queries) GetAuthSessionByID(ctx context.Context, id int32) (AuthSession, error) {
	row := q.db.QueryRow(ctx, getAuthSessionByID, id)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SecretHash,
		&i.LastActiveAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAuthSession = `-- name: DeleteAuthSession :exec
delete from auth_sessions where id = $1
`

func (q *Queries) DeleteAuthSession(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteAuthSession, id)
	return err
}
