// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exercises.sql

package db

import (
	"context"
)

const createExercise = `-- name: CreateExercise :one
insert into exercises (user_id, name)
values ($1, $2)
returning id, user_id, name, index, updated_at, created_at
`

type CreateExerciseParams struct {
	UserID int32
	Name   string
}

func (q *Queries) CreateExercise(ctx context.Context, arg CreateExerciseParams) (Exercise, error) {
	row := q.db.QueryRow(ctx, createExercise, arg.UserID, arg.Name)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Index,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createExerciseTags = `-- name: CreateExerciseTags :exec
insert into exercise_tags (exercise_id, tag_id)
select $1, unnest($2::int[])
`

type CreateExerciseTagsParams struct {
	ExerciseID int32
	Column2    []int32
}

func (q *Queries) CreateExerciseTags(ctx context.Context, arg CreateExerciseTagsParams) error {
	_, err := q.db.Exec(ctx, createExerciseTags, arg.ExerciseID, arg.Column2)
	return err
}

const getExercisesCountByUserID = `-- name: GetExercisesCountByUserID :one
select count(*) from exercises
where user_id = $1
`

func (q *Queries) GetExercisesCountByUserID(ctx context.Context, userID int32) (int64, error) {
	row := q.db.QueryRow(ctx, getExercisesCountByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getExercisesPageByUserID = `-- name: GetExercisesPageByUserID :many
select id, user_id, name, index, updated_at, created_at from exercises
where user_id = $1
  and index < $2
order by index desc
limit $3
`

type GetExercisesPageByUserIDParams struct {
	UserID int32
	Index  int32
	Limit  int32
}

func (q *Queries) GetExercisesPageByUserID(ctx context.Context, arg GetExercisesPageByUserIDParams) ([]Exercise, error) {
	rows, err := q.db.Query(ctx, getExercisesPageByUserID, arg.UserID, arg.Index, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exercise
	for rows.Next() {
		var i Exercise
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Index,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
