// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exercises.sql

package db

import (
	"context"
)

const createExercise = `-- name: CreateExercise :one
insert into exercises (user_id, name)
values ($1, $2)
returning id, user_id, name, index, updated_at, created_at
`

type CreateExerciseParams struct {
	UserID int32
	Name   string
}

func (q *Queries) CreateExercise(ctx context.Context, arg CreateExerciseParams) (Exercise, error) {
	row := q.db.QueryRow(ctx, createExercise, arg.UserID, arg.Name)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Index,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createExerciseTags = `-- name: CreateExerciseTags :exec
insert into exercise_tags (exercise_id, tag_id)
select $1, unnest($2::int[])
`

type CreateExerciseTagsParams struct {
	ExerciseID int32
	Column2    []int32
}

func (q *Queries) CreateExerciseTags(ctx context.Context, arg CreateExerciseTagsParams) error {
	_, err := q.db.Exec(ctx, createExerciseTags, arg.ExerciseID, arg.Column2)
	return err
}
