// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exercises.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createExercise = `-- name: CreateExercise :one
insert into exercises (user_id, name)
values ($1, $2)
returning id, user_id, name, index, updated_at, created_at
`

type CreateExerciseParams struct {
	UserID int32
	Name   string
}

func (q *Queries) CreateExercise(ctx context.Context, arg CreateExerciseParams) (Exercise, error) {
	row := q.db.QueryRow(ctx, createExercise, arg.UserID, arg.Name)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Index,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createExerciseTags = `-- name: CreateExerciseTags :exec
insert into exercise_tags (exercise_id, tag_id)
select $1, unnest($2::int[])
`

type CreateExerciseTagsParams struct {
	ExerciseID int32
	Column2    []int32
}

func (q *Queries) CreateExerciseTags(ctx context.Context, arg CreateExerciseTagsParams) error {
	_, err := q.db.Exec(ctx, createExerciseTags, arg.ExerciseID, arg.Column2)
	return err
}

const deleteExercise = `-- name: DeleteExercise :exec
delete from exercises
where id = $1 and user_id = $2
`

type DeleteExerciseParams struct {
	ID     int32
	UserID int32
}

func (q *Queries) DeleteExercise(ctx context.Context, arg DeleteExerciseParams) error {
	_, err := q.db.Exec(ctx, deleteExercise, arg.ID, arg.UserID)
	return err
}

const deleteExerciseTags = `-- name: DeleteExerciseTags :exec
delete from exercise_tags where exercise_id = $1
`

func (q *Queries) DeleteExerciseTags(ctx context.Context, exerciseID int32) error {
	_, err := q.db.Exec(ctx, deleteExerciseTags, exerciseID)
	return err
}

const getAllExercisesByUserID = `-- name: GetAllExercisesByUserID :many
select id, user_id, name, index, updated_at, created_at from exercises
where user_id = $1
order by index asc
`

func (q *Queries) GetAllExercisesByUserID(ctx context.Context, userID int32) ([]Exercise, error) {
	rows, err := q.db.Query(ctx, getAllExercisesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exercise
	for rows.Next() {
		var i Exercise
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Index,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExerciseByIDAndUserID = `-- name: GetExerciseByIDAndUserID :one
select id, user_id, name, index, updated_at, created_at from exercises
where id = $1 and user_id = $2
`

type GetExerciseByIDAndUserIDParams struct {
	ID     int32
	UserID int32
}

func (q *Queries) GetExerciseByIDAndUserID(ctx context.Context, arg GetExerciseByIDAndUserIDParams) (Exercise, error) {
	row := q.db.QueryRow(ctx, getExerciseByIDAndUserID, arg.ID, arg.UserID)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Index,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getExercisesCountByUserID = `-- name: GetExercisesCountByUserID :one
select count(*) from exercises
where user_id = $1
`

func (q *Queries) GetExercisesCountByUserID(ctx context.Context, userID int32) (int64, error) {
	row := q.db.QueryRow(ctx, getExercisesCountByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getExercisesPageByUserID = `-- name: GetExercisesPageByUserID :many
SELECT
    e.id, 
    e.user_id, 
    e.name, 
    e.index, 
    e.updated_at, 
    e.created_at,
    COALESCE(s.sets_count, 0) AS sets_count,
    s.last_set_weight_in_g,
    s.last_set_repetitions,
    s.last_set_done_at,
    s.prev_set_weight_in_g,
    s.prev_set_repetitions
FROM exercises e
LEFT JOIN LATERAL (
    SELECT
        COUNT(*) AS sets_count,
        -- Extract the 1st row's data
        COALESCE(MAX(weight_in_g) FILTER (WHERE rn = 1), 0)::int AS last_set_weight_in_g,
        COALESCE(MAX(repetitions) FILTER (WHERE rn = 1), 0)::int AS last_set_repetitions,
        MAX(done_at) FILTER (WHERE rn = 1)::timestamptz AS last_set_done_at,
        -- Extract the 2nd row's data
        COALESCE(MAX(weight_in_g) FILTER (WHERE rn = 2), 0)::int AS prev_set_weight_in_g,
        COALESCE(MAX(repetitions) FILTER (WHERE rn = 2), 0)::int AS prev_set_repetitions
    FROM (
        SELECT
            weight_in_g,
            repetitions,
            done_at,
            ROW_NUMBER() OVER (ORDER BY created_at DESC) as rn
        FROM sets
        WHERE exercise_id = e.id
    ) ranked_sets
) s ON true
WHERE e.user_id = $1
  AND e.index < $2
ORDER BY e.index DESC
LIMIT $3
`

type GetExercisesPageByUserIDParams struct {
	UserID int32
	Index  int32
	Limit  int32
}

type GetExercisesPageByUserIDRow struct {
	ID                 int32
	UserID             int32
	Name               string
	Index              int32
	UpdatedAt          pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	SetsCount          int64
	LastSetWeightInG   int32
	LastSetRepetitions int32
	LastSetDoneAt      pgtype.Timestamptz
	PrevSetWeightInG   int32
	PrevSetRepetitions int32
}

func (q *Queries) GetExercisesPageByUserID(ctx context.Context, arg GetExercisesPageByUserIDParams) ([]GetExercisesPageByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getExercisesPageByUserID, arg.UserID, arg.Index, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExercisesPageByUserIDRow
	for rows.Next() {
		var i GetExercisesPageByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Index,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.SetsCount,
			&i.LastSetWeightInG,
			&i.LastSetRepetitions,
			&i.LastSetDoneAt,
			&i.PrevSetWeightInG,
			&i.PrevSetRepetitions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExerciseName = `-- name: UpdateExerciseName :one
update exercises
set name = $1, updated_at = now()
where id = $2 and user_id = $3
returning id, user_id, name, index, updated_at, created_at
`

type UpdateExerciseNameParams struct {
	Name   string
	ID     int32
	UserID int32
}

func (q *Queries) UpdateExerciseName(ctx context.Context, arg UpdateExerciseNameParams) (Exercise, error) {
	row := q.db.QueryRow(ctx, updateExerciseName, arg.Name, arg.ID, arg.UserID)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Index,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}
