// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type OneRepMaxAlgorithm string

const (
	OneRepMaxAlgorithmAdams    OneRepMaxAlgorithm = "adams"
	OneRepMaxAlgorithmBaechle  OneRepMaxAlgorithm = "baechle"
	OneRepMaxAlgorithmBerger   OneRepMaxAlgorithm = "berger"
	OneRepMaxAlgorithmBrown    OneRepMaxAlgorithm = "brown"
	OneRepMaxAlgorithmBrzycki  OneRepMaxAlgorithm = "brzycki"
	OneRepMaxAlgorithmEpley    OneRepMaxAlgorithm = "epley"
	OneRepMaxAlgorithmKemmler  OneRepMaxAlgorithm = "kemmler"
	OneRepMaxAlgorithmLanders  OneRepMaxAlgorithm = "landers"
	OneRepMaxAlgorithmLombardi OneRepMaxAlgorithm = "lombardi"
	OneRepMaxAlgorithmMayhew   OneRepMaxAlgorithm = "mayhew"
	OneRepMaxAlgorithmNaclerio OneRepMaxAlgorithm = "naclerio"
	OneRepMaxAlgorithmOconner  OneRepMaxAlgorithm = "oconner"
	OneRepMaxAlgorithmWathen   OneRepMaxAlgorithm = "wathen"
)

func (e *OneRepMaxAlgorithm) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OneRepMaxAlgorithm(s)
	case string:
		*e = OneRepMaxAlgorithm(s)
	default:
		return fmt.Errorf("unsupported scan type for OneRepMaxAlgorithm: %T", src)
	}
	return nil
}

type NullOneRepMaxAlgorithm struct {
	OneRepMaxAlgorithm OneRepMaxAlgorithm
	Valid              bool // Valid is true if OneRepMaxAlgorithm is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOneRepMaxAlgorithm) Scan(value interface{}) error {
	if value == nil {
		ns.OneRepMaxAlgorithm, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OneRepMaxAlgorithm.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOneRepMaxAlgorithm) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OneRepMaxAlgorithm), nil
}

type WeightUnit string

const (
	WeightUnitKg  WeightUnit = "kg"
	WeightUnitLbs WeightUnit = "lbs"
)

func (e *WeightUnit) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WeightUnit(s)
	case string:
		*e = WeightUnit(s)
	default:
		return fmt.Errorf("unsupported scan type for WeightUnit: %T", src)
	}
	return nil
}

type NullWeightUnit struct {
	WeightUnit WeightUnit
	Valid      bool // Valid is true if WeightUnit is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWeightUnit) Scan(value interface{}) error {
	if value == nil {
		ns.WeightUnit, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WeightUnit.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWeightUnit) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WeightUnit), nil
}

type AccountDeletionSession struct {
	ID                     int32
	AuthSessionID          int32
	SecretHash             []byte
	UserIdentityVerifiedAt pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
}

type AuthSession struct {
	ID           int32
	UserID       int32
	SecretHash   []byte
	LastActiveAt pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Exercise struct {
	ID        int32
	UserID    int32
	Name      string
	UpdatedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type ExerciseTag struct {
	ExerciseID int32
	TagID      int32
	CreatedAt  pgtype.Timestamptz
}

type PasswordResetSession struct {
	ID                     int32
	UserID                 int32
	SecretHash             []byte
	EmailCodeHash          []byte
	EmailCodeSalt          []byte
	UserIdentityVerifiedAt pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
}

type PasswordUpdateSession struct {
	ID                     int32
	AuthSessionID          int32
	SecretHash             []byte
	UserIdentityVerifiedAt pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
}

type Set struct {
	ID          int32
	ExerciseID  int32
	Repetitions int32
	WeightInG   int32
	DoneAt      pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

type SignUpSession struct {
	ID                           int32
	SecretHash                   []byte
	EmailAddress                 string
	EmailAddressVerificationCode string
	EmailAddressVerifiedAt       pgtype.Timestamptz
	CreatedAt                    pgtype.Timestamptz
	UpdatedAt                    pgtype.Timestamptz
}

type Tag struct {
	ID        int32
	UserID    int32
	Name      string
	UpdatedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID                 int32
	EmailAddress       string
	Name               string
	WeightUnit         WeightUnit
	OneRepMaxAlgorithm OneRepMaxAlgorithm
	PasswordHash       []byte
	PasswordSalt       []byte
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}
