// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSets = `-- name: CreateSets :many
insert into sets (exercise_id, repetitions, weight_in_g)
select unnest($1::int[]), unnest($2::int[]), unnest($3::int[])
returning id, exercise_id, repetitions, weight_in_g, done_at, updated_at, created_at
`

type CreateSetsParams struct {
	Column1 []int32
	Column2 []int32
	Column3 []int32
}

func (q *Queries) CreateSets(ctx context.Context, arg CreateSetsParams) ([]Set, error) {
	rows, err := q.db.Query(ctx, createSets, arg.Column1, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Set
	for rows.Next() {
		var i Set
		if err := rows.Scan(
			&i.ID,
			&i.ExerciseID,
			&i.Repetitions,
			&i.WeightInG,
			&i.DoneAt,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteSetByIDAndUserID = `-- name: DeleteSetByIDAndUserID :exec
delete from sets
using exercises
where sets.id = $1
  and sets.exercise_id = exercises.id
  and exercises.user_id = $2
`

type DeleteSetByIDAndUserIDParams struct {
	ID     int32
	UserID int32
}

func (q *Queries) DeleteSetByIDAndUserID(ctx context.Context, arg DeleteSetByIDAndUserIDParams) error {
	_, err := q.db.Exec(ctx, deleteSetByIDAndUserID, arg.ID, arg.UserID)
	return err
}

const getExerciseStatsByID = `-- name: GetExerciseStatsByID :one
select
    count(*)::int                               as total_sets,
    coalesce(max(weight_in_g), 0)::int          as highest_weight_in_g,
    coalesce(sum(weight_in_g::bigint * repetitions::bigint), 0)::bigint as total_volume_in_g
from sets
where exercise_id = $1
`

type GetExerciseStatsByIDRow struct {
	TotalSets        int32
	HighestWeightInG int32
	TotalVolumeInG   int64
}

func (q *Queries) GetExerciseStatsByID(ctx context.Context, exerciseID int32) (GetExerciseStatsByIDRow, error) {
	row := q.db.QueryRow(ctx, getExerciseStatsByID, exerciseID)
	var i GetExerciseStatsByIDRow
	err := row.Scan(&i.TotalSets, &i.HighestWeightInG, &i.TotalVolumeInG)
	return i, err
}

const getLastSetByExerciseID = `-- name: GetLastSetByExerciseID :one
select id, exercise_id, repetitions, weight_in_g, done_at, updated_at, created_at
from sets
where exercise_id = $1
order by done_at desc
limit 1
`

func (q *Queries) GetLastSetByExerciseID(ctx context.Context, exerciseID int32) (Set, error) {
	row := q.db.QueryRow(ctx, getLastSetByExerciseID, exerciseID)
	var i Set
	err := row.Scan(
		&i.ID,
		&i.ExerciseID,
		&i.Repetitions,
		&i.WeightInG,
		&i.DoneAt,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSetByIDAndUserID = `-- name: GetSetByIDAndUserID :one
select s.id, s.exercise_id, s.repetitions, s.weight_in_g, s.done_at, s.updated_at, s.created_at
from sets s
join exercises e on e.id = s.exercise_id
where s.id = $1
  and e.user_id = $2
`

type GetSetByIDAndUserIDParams struct {
	ID     int32
	UserID int32
}

func (q *Queries) GetSetByIDAndUserID(ctx context.Context, arg GetSetByIDAndUserIDParams) (Set, error) {
	row := q.db.QueryRow(ctx, getSetByIDAndUserID, arg.ID, arg.UserID)
	var i Set
	err := row.Scan(
		&i.ID,
		&i.ExerciseID,
		&i.Repetitions,
		&i.WeightInG,
		&i.DoneAt,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSetsByExerciseID = `-- name: GetSetsByExerciseID :many
select id, exercise_id, repetitions, weight_in_g, done_at, updated_at, created_at
from sets
where exercise_id = $1
order by done_at asc
`

func (q *Queries) GetSetsByExerciseID(ctx context.Context, exerciseID int32) ([]Set, error) {
	rows, err := q.db.Query(ctx, getSetsByExerciseID, exerciseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Set
	for rows.Next() {
		var i Set
		if err := rows.Scan(
			&i.ID,
			&i.ExerciseID,
			&i.Repetitions,
			&i.WeightInG,
			&i.DoneAt,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSetsPageByExerciseID = `-- name: GetSetsPageByExerciseID :many
select id, exercise_id, repetitions, weight_in_g, done_at, updated_at, created_at
from sets
where exercise_id = $1
  and id < $2
order by done_at desc
limit $3
`

type GetSetsPageByExerciseIDParams struct {
	ExerciseID int32
	ID         int32
	Limit      int32
}

func (q *Queries) GetSetsPageByExerciseID(ctx context.Context, arg GetSetsPageByExerciseIDParams) ([]Set, error) {
	rows, err := q.db.Query(ctx, getSetsPageByExerciseID, arg.ExerciseID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Set
	for rows.Next() {
		var i Set
		if err := rows.Scan(
			&i.ID,
			&i.ExerciseID,
			&i.Repetitions,
			&i.WeightInG,
			&i.DoneAt,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seedCreateSets = `-- name: SeedCreateSets :exec
insert into sets (exercise_id, repetitions, weight_in_g, done_at, created_at, updated_at)
select $1, unnest($2::int[]), unnest($3::int[]), unnest($4::timestamptz[]), unnest($4::timestamptz[]), unnest($4::timestamptz[])
`

type SeedCreateSetsParams struct {
	ExerciseID int32
	Column2    []int32
	Column3    []int32
	Column4    []pgtype.Timestamptz
}

func (q *Queries) SeedCreateSets(ctx context.Context, arg SeedCreateSetsParams) error {
	_, err := q.db.Exec(ctx, seedCreateSets,
		arg.ExerciseID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	return err
}

const updateSetByIDAndUserID = `-- name: UpdateSetByIDAndUserID :one
update sets s
set repetitions = $3, weight_in_g = $4, done_at = $5, updated_at = now()
from exercises e
where s.id = $1
  and s.exercise_id = e.id
  and e.user_id = $2
returning s.id, s.exercise_id, s.repetitions, s.weight_in_g, s.done_at, s.updated_at, s.created_at
`

type UpdateSetByIDAndUserIDParams struct {
	ID          int32
	UserID      int32
	Repetitions int32
	WeightInG   int32
	DoneAt      pgtype.Timestamptz
}

func (q *Queries) UpdateSetByIDAndUserID(ctx context.Context, arg UpdateSetByIDAndUserIDParams) (Set, error) {
	row := q.db.QueryRow(ctx, updateSetByIDAndUserID,
		arg.ID,
		arg.UserID,
		arg.Repetitions,
		arg.WeightInG,
		arg.DoneAt,
	)
	var i Set
	err := row.Scan(
		&i.ID,
		&i.ExerciseID,
		&i.Repetitions,
		&i.WeightInG,
		&i.DoneAt,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}
