// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package db

import (
	"context"
)

const countTagsByUserID = `-- name: CountTagsByUserID :one
select count(*)::int from tags
where user_id = $1
`

func (q *Queries) CountTagsByUserID(ctx context.Context, userID int32) (int32, error) {
	row := q.db.QueryRow(ctx, countTagsByUserID, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createTag = `-- name: CreateTag :one
insert into tags (user_id, name)
values ($1, $2)
returning id, user_id, name, updated_at, created_at
`

type CreateTagParams struct {
	UserID int32
	Name   string
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, createTag, arg.UserID, arg.Name)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createTags = `-- name: CreateTags :many
insert into tags (user_id, name)
select $1, unnest($2::text[])
returning id, user_id, name, updated_at, created_at
`

type CreateTagsParams struct {
	UserID  int32
	Column2 []string
}

func (q *Queries) CreateTags(ctx context.Context, arg CreateTagsParams) ([]Tag, error) {
	rows, err := q.db.Query(ctx, createTags, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteTag = `-- name: DeleteTag :exec
delete from tags
where id = $1 and user_id = $2
`

type DeleteTagParams struct {
	ID     int32
	UserID int32
}

func (q *Queries) DeleteTag(ctx context.Context, arg DeleteTagParams) error {
	_, err := q.db.Exec(ctx, deleteTag, arg.ID, arg.UserID)
	return err
}

const getAllExerciseTagNamesByUserID = `-- name: GetAllExerciseTagNamesByUserID :many
select et.exercise_id, t.name
from exercise_tags et
inner join tags t on t.id = et.tag_id
inner join exercises e on e.id = et.exercise_id
where e.user_id = $1
order by et.exercise_id asc, t.name asc
`

type GetAllExerciseTagNamesByUserIDRow struct {
	ExerciseID int32
	Name       string
}

func (q *Queries) GetAllExerciseTagNamesByUserID(ctx context.Context, userID int32) ([]GetAllExerciseTagNamesByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getAllExerciseTagNamesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllExerciseTagNamesByUserIDRow
	for rows.Next() {
		var i GetAllExerciseTagNamesByUserIDRow
		if err := rows.Scan(&i.ExerciseID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTagByID = `-- name: GetTagByID :one
select id, user_id, name, updated_at, created_at from tags
where id = $1 and user_id = $2
`

type GetTagByIDParams struct {
	ID     int32
	UserID int32
}

func (q *Queries) GetTagByID(ctx context.Context, arg GetTagByIDParams) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagByID, arg.ID, arg.UserID)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getTagsByExerciseID = `-- name: GetTagsByExerciseID :many
select t.id, t.user_id, t.name, t.updated_at, t.created_at from tags t
inner join exercise_tags et on et.tag_id = t.id
where et.exercise_id = $1
order by t.name asc
`

func (q *Queries) GetTagsByExerciseID(ctx context.Context, exerciseID int32) ([]Tag, error) {
	rows, err := q.db.Query(ctx, getTagsByExerciseID, exerciseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTagsByUserID = `-- name: GetTagsByUserID :many
select id, user_id, name, updated_at, created_at from tags
where user_id = $1
order by name asc
`

func (q *Queries) GetTagsByUserID(ctx context.Context, userID int32) ([]Tag, error) {
	rows, err := q.db.Query(ctx, getTagsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTagsPageByUserID = `-- name: GetTagsPageByUserID :many
select id, user_id, name, updated_at, created_at from tags
where user_id = $1
  and name > $2
order by name asc
limit $3
`

type GetTagsPageByUserIDParams struct {
	UserID int32
	Name   string
	Limit  int32
}

func (q *Queries) GetTagsPageByUserID(ctx context.Context, arg GetTagsPageByUserIDParams) ([]Tag, error) {
	rows, err := q.db.Query(ctx, getTagsPageByUserID, arg.UserID, arg.Name, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTagName = `-- name: UpdateTagName :one
update tags
set name = $1, updated_at = now()
where id = $2 and user_id = $3
returning id, user_id, name, updated_at, created_at
`

type UpdateTagNameParams struct {
	Name   string
	ID     int32
	UserID int32
}

func (q *Queries) UpdateTagName(ctx context.Context, arg UpdateTagNameParams) (Tag, error) {
	row := q.db.QueryRow(ctx, updateTagName, arg.Name, arg.ID, arg.UserID)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsertTags = `-- name: UpsertTags :many
insert into tags (user_id, name)
select $1, unnest($2::text[])
on conflict (user_id, name) do update set name = excluded.name
returning id, user_id, name, updated_at, created_at
`

type UpsertTagsParams struct {
	UserID  int32
	Column2 []string
}

func (q *Queries) UpsertTags(ctx context.Context, arg UpsertTagsParams) ([]Tag, error) {
	rows, err := q.db.Query(ctx, upsertTags, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
