// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package db

import (
	"context"
)

const getTagsByUserID = `-- name: GetTagsByUserID :many
select id, user_id, name, updated_at, created_at from tags
where user_id = $1
order by name asc
`

func (q *Queries) GetTagsByUserID(ctx context.Context, userID int32) ([]Tag, error) {
	rows, err := q.db.Query(ctx, getTagsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
