// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
insert into users (email_address, password_hash, password_salt, name)
select
    email_address,
    $1,
    $2,
    $3
from sign_up_sessions
where sign_up_sessions.id = $4 and email_address_verified_at is not null returning
    id, email_address
`

type CreateUserParams struct {
	PasswordHash []byte
	PasswordSalt []byte
	Name         string
	ID           int32
}

type CreateUserRow struct {
	ID           int32
	EmailAddress string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.PasswordHash,
		arg.PasswordSalt,
		arg.Name,
		arg.ID,
	)
	var i CreateUserRow
	err := row.Scan(&i.ID, &i.EmailAddress)
	return i, err
}

const deleteUserByAccountDeletionSessionID = `-- name: DeleteUserByAccountDeletionSessionID :one
delete from users
where id in (
    select auth_sessions.user_id
    from auth_sessions
    inner join account_deletion_sessions
        on auth_sessions.id = account_deletion_sessions.auth_session_id
    where account_deletion_sessions.id = $1
    and account_deletion_sessions.user_identity_verified_at is not null
)
returning id, email_address, name, weight_unit, password_hash, password_salt, created_at, updated_at, one_rep_max_algorithm
`

func (q *Queries) DeleteUserByAccountDeletionSessionID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, deleteUserByAccountDeletionSessionID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.EmailAddress,
		&i.Name,
		&i.WeightUnit,
		&i.PasswordHash,
		&i.PasswordSalt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OneRepMaxAlgorithm,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
select id, email_address, name, weight_unit, password_hash, password_salt, created_at, updated_at, one_rep_max_algorithm from users
where email_address = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, emailAddress string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, emailAddress)
	var i User
	err := row.Scan(
		&i.ID,
		&i.EmailAddress,
		&i.Name,
		&i.WeightUnit,
		&i.PasswordHash,
		&i.PasswordSalt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OneRepMaxAlgorithm,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
select id, email_address, name, weight_unit, password_hash, password_salt, created_at, updated_at, one_rep_max_algorithm from users
where id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.EmailAddress,
		&i.Name,
		&i.WeightUnit,
		&i.PasswordHash,
		&i.PasswordSalt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OneRepMaxAlgorithm,
	)
	return i, err
}

const getUserByPasswordResetSessionID = `-- name: GetUserByPasswordResetSessionID :one
select users.id, users.email_address, users.name, users.weight_unit, users.password_hash, users.password_salt, users.created_at, users.updated_at, users.one_rep_max_algorithm from users
join password_reset_sessions on password_reset_sessions.user_id = users.id
where password_reset_sessions.id = $1
`

func (q *Queries) GetUserByPasswordResetSessionID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPasswordResetSessionID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.EmailAddress,
		&i.Name,
		&i.WeightUnit,
		&i.PasswordHash,
		&i.PasswordSalt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OneRepMaxAlgorithm,
	)
	return i, err
}

const updateUserName = `-- name: UpdateUserName :exec
update users
set name = $1
where id = $2
`

type UpdateUserNameParams struct {
	Name string
	ID   int32
}

func (q *Queries) UpdateUserName(ctx context.Context, arg UpdateUserNameParams) error {
	_, err := q.db.Exec(ctx, updateUserName, arg.Name, arg.ID)
	return err
}

const updateUserPasswordByPasswordResetSessionID = `-- name: UpdateUserPasswordByPasswordResetSessionID :exec
update users
set
  password_hash = $1,
  password_salt = $2
from password_reset_sessions
where users.id = password_reset_sessions.user_id
    and password_reset_sessions.id = $3
    and password_reset_sessions.user_identity_verified_at is not null
returning password_reset_sessions.id
`

type UpdateUserPasswordByPasswordResetSessionIDParams struct {
	PasswordHash []byte
	PasswordSalt []byte
	ID           int32
}

func (q *Queries) UpdateUserPasswordByPasswordResetSessionID(ctx context.Context, arg UpdateUserPasswordByPasswordResetSessionIDParams) error {
	_, err := q.db.Exec(ctx, updateUserPasswordByPasswordResetSessionID, arg.PasswordHash, arg.PasswordSalt, arg.ID)
	return err
}

const updateUserPasswordByPasswordUpdateSessionID = `-- name: UpdateUserPasswordByPasswordUpdateSessionID :exec
update users
set
    password_hash = $1,
    password_salt = $2
from auth_sessions
join password_update_sessions on password_update_sessions.auth_session_id = auth_sessions.id
where users.id = auth_sessions.user_id
  and auth_sessions.id = password_update_sessions.auth_session_id
  and password_update_sessions.id = $3
  and password_update_sessions.user_identity_verified_at is not null
returning users.id
`

type UpdateUserPasswordByPasswordUpdateSessionIDParams struct {
	PasswordHash []byte
	PasswordSalt []byte
	ID           int32
}

func (q *Queries) UpdateUserPasswordByPasswordUpdateSessionID(ctx context.Context, arg UpdateUserPasswordByPasswordUpdateSessionIDParams) error {
	_, err := q.db.Exec(ctx, updateUserPasswordByPasswordUpdateSessionID, arg.PasswordHash, arg.PasswordSalt, arg.ID)
	return err
}

const updateUserWeightUnit = `-- name: UpdateUserWeightUnit :exec
update users
set weight_unit = $1
where id = $2
`

type UpdateUserWeightUnitParams struct {
	WeightUnit WeightUnit
	ID         int32
}

func (q *Queries) UpdateUserWeightUnit(ctx context.Context, arg UpdateUserWeightUnitParams) error {
	_, err := q.db.Exec(ctx, updateUserWeightUnit, arg.WeightUnit, arg.ID)
	return err
}
