// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sign_up_sessions.sql

package sqlc

import (
	"context"
)

const createSignUpSession = `-- name: CreateSignUpSession :one
insert into sign_up_sessions (secret_hash, email_address, email_address_verification_code)
values ($1, $2, $3)
returning id, secret_hash, email_address, email_address_verification_code, email_address_verified_at, created_at, updated_at
`

type CreateSignUpSessionParams struct {
	SecretHash                   []byte
	EmailAddress                 string
	EmailAddressVerificationCode string
}

func (q *Queries) CreateSignUpSession(ctx context.Context, arg CreateSignUpSessionParams) (SignUpSession, error) {
	row := q.db.QueryRow(ctx, createSignUpSession, arg.SecretHash, arg.EmailAddress, arg.EmailAddressVerificationCode)
	var i SignUpSession
	err := row.Scan(
		&i.ID,
		&i.SecretHash,
		&i.EmailAddress,
		&i.EmailAddressVerificationCode,
		&i.EmailAddressVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSignUpSession = `-- name: DeleteSignUpSession :one
delete from sign_up_sessions where id = $1 returning id, secret_hash, email_address, email_address_verification_code, email_address_verified_at, created_at, updated_at
`

func (q *Queries) DeleteSignUpSession(ctx context.Context, id int32) (SignUpSession, error) {
	row := q.db.QueryRow(ctx, deleteSignUpSession, id)
	var i SignUpSession
	err := row.Scan(
		&i.ID,
		&i.SecretHash,
		&i.EmailAddress,
		&i.EmailAddressVerificationCode,
		&i.EmailAddressVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSignUpSessionByID = `-- name: GetSignUpSessionByID :one
select id, secret_hash, email_address, email_address_verification_code, email_address_verified_at, created_at, updated_at from sign_up_sessions where id = $1 and created_at > now() - interval '24 hours'
`

func (q *Queries) GetSignUpSessionByID(ctx context.Context, id int32) (SignUpSession, error) {
	row := q.db.QueryRow(ctx, getSignUpSessionByID, id)
	var i SignUpSession
	err := row.Scan(
		&i.ID,
		&i.SecretHash,
		&i.EmailAddress,
		&i.EmailAddressVerificationCode,
		&i.EmailAddressVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const verifySignUpSession = `-- name: VerifySignUpSession :one
update 
  sign_up_sessions 
set 
  email_address_verified_at = now() 
where 
  id = $1 
  and email_address_verified_at is null 
returning 
  id, secret_hash, email_address, email_address_verification_code, email_address_verified_at, created_at, updated_at
`

func (q *Queries) VerifySignUpSession(ctx context.Context, id int32) (SignUpSession, error) {
	row := q.db.QueryRow(ctx, verifySignUpSession, id)
	var i SignUpSession
	err := row.Scan(
		&i.ID,
		&i.SecretHash,
		&i.EmailAddress,
		&i.EmailAddressVerificationCode,
		&i.EmailAddressVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
