// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"
)

const createUser = `-- name: CreateUser :one
insert into users (email_address, name, weight_unit, password_hash, password_salt)
values ($1, $2, $3, $4, $5)
returning id, email_address, name, weight_unit, password_hash, password_salt, created_at, updated_at, one_rep_max_algorithm
`

type CreateUserParams struct {
	EmailAddress string
	Name         string
	WeightUnit   WeightUnit
	PasswordHash []byte
	PasswordSalt []byte
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.EmailAddress,
		arg.Name,
		arg.WeightUnit,
		arg.PasswordHash,
		arg.PasswordSalt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.EmailAddress,
		&i.Name,
		&i.WeightUnit,
		&i.PasswordHash,
		&i.PasswordSalt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OneRepMaxAlgorithm,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
select id, email_address, name, weight_unit, password_hash, password_salt, created_at, updated_at, one_rep_max_algorithm from users
where email_address = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, emailAddress string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, emailAddress)
	var i User
	err := row.Scan(
		&i.ID,
		&i.EmailAddress,
		&i.Name,
		&i.WeightUnit,
		&i.PasswordHash,
		&i.PasswordSalt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OneRepMaxAlgorithm,
	)
	return i, err
}
